### ISSUE TITLE
Feature request: do not display older core versions

### ISSUE THREAD

**Issue by cb2004** [ryancramerdesign/ProcessWireUpgrade#27]
There are 6 core versions that are displayed for me but I am only interested in the latest dev and master. Could there be some configuration added which allows what core versions to display?

**Comment by franctic-aerobic** [comment]
I'd also like to see only the latest version, e.g. these:
ProcessWire Core (Dev) | ProcessWire dev | 
ProcessWire Core (Master) | ProcessWire master | 

And not these:
ProcessWire Core (Legacy/Master) | ProcessWire legacy-master | 
ProcessWire Core (Prev/Dev) | ProcessWire prev-dev | 
ProcessWire Core (Prev/Devns) | ProcessWire prev-devns | 3.0
ProcessWire Core (Prev/Master)

Maybe there could be a settings panel where one could select/deselect every module that could be visible in the Upgrades module? So that one could also hide other modules.

**Comment by matjazpotocnik** [comment]
There is no config option for that, but since this module is not very actively maintained, you can modify source file ProcessWireUpgradeCheck.module and comment out legacy and prev repos.
